### ISSUE TITLE
Can't find a "bRigNet" tab after I enable the add-on in blender

### ISSUE THREAD

**Issue by crissallan** [pKrime/brignet#1]
Hi, I've followed your intro about the installation of the bRigNet add-on. but I can't find a "bRigNet" tab after I enable the add-on in blender. Could you please make the intro more specific? 

Besides, I don't quite understand the meaning of the state "Set the Modules path properties to the RigNet environment from the previous step" in the "Usage"  part in your README. Does that mean I should set this property as a venv folder of python? or the RigNet original project?

Many thanks!

**Comment by pKrime** [comment]
Hi,

if you press "N" in the viewport blender will show up the properties tabs. Default tabs are "Item", "Tool", "View". If bRigNet is enabled, the bRigNet tab should follow, does it show up?

![brignet_tab](https://user-images.githubusercontent.com/5176115/100069096-9f43d080-2e38-11eb-960f-7796141807d4.jpg)

About the modules path, once the addon is enabled you should be able to see the bRigNet preferences just below the addon entry

![brignet_settings](https://user-images.githubusercontent.com/5176115/100069256-d4502300-2e38-11eb-99e3-5b5ed284adf9.jpg)
 
In my case I entered the path to the conda environment, but virtualenv should do just fine

Cheers!

**Comment by crissallan** [comment]
Oh, it  solved my problems! 
Cheers!

**Comment by ibtehajali67** [comment]
> 

can you please help me I tried my best but I am stuck in one prblem
