### ISSUE TITLE
Need Help with Location setting in addon preferences

### ISSUE THREAD

**Issue by gSingh-maker** [pKrime/brignet#10]
> "Set the Modules path properties to the RigNet environment from the previous step"
Do you mean the environment inside anaconda ? Something like  .\Anaconda3\envs\rignet\
I should paste that address in Modules path ?

> "The checkpoint folder can be copied to the RigNet subfolder. A different location can be set in the addon preferences."
I have downloaded and extracted both RigNet and bRigNet. 
There is a RigNet folder inside bRigNet as well. Do we need to copy checkpoints folder to it, or we need to set the path to actual RigNet directory ?

Can you please help me with setting the Location path properties..

Thanks in advance.

**Comment by pKrime** [comment]
Hi,

you are correct, you can use your anaconda or venv path in the settings. There is a copy of RigNet inside the addon, and that is the default location of the checkpoint folder, but you can use other location too

regards!

**Comment by pKrime** [comment]
Hi, the latest version of the addon comes with more detailed info and an autoinstall script. I hope that can help easing the process

Cheers,
Paolo
