### ISSUE TITLE
Error with LoadSkeleton

### ISSUE THREAD

**Issue by gSingh-maker** [pKrime/brignet#11]
I get the following error while trying to run the "Load RigNet Character".

![Capture](https://user-images.githubusercontent.com/82636358/115360830-a00d4280-a1dd-11eb-869c-3f0f5fbc7b15.PNG)

RigNet is working fine. 
I want to combine the .obj with .txt file.
My system does not have GPU.(Windows 10)

Online solutions suggested to have Blender in "Object mode", instead of "Edit mode". But mine is in "Object mode" only.
The Blender version is 2.92.

Thanks!

**Comment by pKrime** [comment]
Hi, proabably the import operator has changed in blender 2.92 and it doesn't accept the global_clight_size parameter anymore. I have removed it from the script and now it should work.

You can either download the addon again, or edit the file yourself and change the line 47 of loadskeleton.py from

`global_clight_size=0, axis_forward='-Z', axis_up='Y')`

to

`axis_forward='-Z', axis_up='Y')`

cheers!

**Comment by gSingh-maker** [comment]
Thank You !
