### ISSUE TITLE
RigNet pack installation

### ISSUE THREAD

**Issue by marcomameli1992** [pKrime/brignet#14]
Dear, 
Iwould like to know hot do you use the RigNet code inside Blender because I'm trying to install the torch-scatter package but it give me an error on the weheel.

Can you help me? Can you show me hoe do you configure the blender python environment with the packages required from RigNet. If ou do not use the Blender python version how can I use a different version og the python managed by conda for esampele.

**Comment by pKrime** [comment]
Ciao Marco,

please check the latest release: there is an auto installer and more detailed information for conda/virtualenv environments.

P.S. until a few weeks ago, you had to install torch-scatter 1.7.0 or 1.8.0 even with pytorch 1.7.1/1.8.1, that generated confusion with some users.

As it is fixed now, you might have solved your issue already

Cheers,
Paolo
