### ISSUE TITLE
I don't have cuda in my machine is it possible to run brignet 

### ISSUE THREAD

**Issue by ibtehajali67** [pKrime/brignet#24]
I wanna run without cuda.

**Comment by pKrime** [comment]
Hi, theoretically it's possible to make torch use the 'cpu', it has not been tested though. I will see if it can be a setting

**Comment by ibtehajali67** [comment]
I have run RIGNET repo without GPU and trying to use this also

**Comment by ibtehajali67** [comment]
I am trying to run on CPU but facing that issue
![error](https://user-images.githubusercontent.com/49198838/199225022-983e062e-4fce-4c88-b2c8-a52076671a4b.png)

**Comment by ibtehajali67** [comment]
> Hi, theoretically it's possible to make torch use the 'cpu', it has not been tested though. I will see if it can be a setting

I have run RIGNet on cpu device but still stuck on this repo. I need your help
thanks in advance
