### ISSUE TITLE
Can't predict joints and skinning

### ISSUE THREAD

**Issue by Bin-Ji** [pKrime/brignet#5]
Thanks for your great work !
when I try to predict joints and skinning, I have the following problems. It seems that something wrong with my Python environment, but it works well for RigNet. 
![image](https://user-images.githubusercontent.com/34656350/102596238-ca0c0680-4110-11eb-8bb8-7295c8abb725.png)

**Comment by pKrime** [comment]
Hi, 

it is possible that some compiled libraries from your env cannot be used in combination with the blender interpreter: in my case I had to install a different version of the Pillow library.

the user Eritojai from the blenderartists forum has posted a step-list that works for his system, perhaps that will work better for you

https://blenderartists.org/t/brignet-neural-rigging-for-blender/1267223/23

P.S. if you are successfull with RigNet standalone, you can load the resulting .obj and skeleton in the "Load Skeleton" panel. I know it's not the same thing, but it can be viable until we reduce the dependencies

Cheers,
p.

**Comment by pKrime** [comment]
Hi,

the latest release cuts the dependencies and has optional auto-setup, please have a try

Cheers,
Paolo
