### ISSUE TITLE
error

### ISSUE THREAD

**Issue by imozi1999** [pKrime/brignet#6]
Helllo!
Thankyou for your great work, im currently getting this weird error that i dont understand, could u help?

![Screenshot from 2020-12-29 18-05-47](https://user-images.githubusercontent.com/55843525/103279524-94b0c400-4a00-11eb-97c5-65a35716a5b8.png)

**Comment by pKrime** [comment]
Hi, it would seem a problem between that version of open3d and python 3.0. I should try to run on Ubuntu to know better, but I would rather ditch the dependency from open3d entirely

**Comment by pKrime** [comment]
Hi,

open3d is not needed anymore. Now it should either work or give a different error

Cheers,
Paolo
