### ISSUE TITLE
Some modules not found, please check bRigNet preferences

### ISSUE THREAD

**Issue by mitchellgordon95** [pKrime/brignet#7]
I am not sure what this step means: "Enable bRigNet in the blender addons, the preferences will show up. Set the Modules path properties to the RigNet environment from the previous step."

I have tried setting this to:

C:\Program Files\Blender Foundation\Blender 2.91\2.91\python
C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin
C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib

C:\Users\mitch\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\brignet-main
C:\Users\mitch\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\brignet-main\RigNet

But none of them seem to resolve the error.

**Comment by xiaochuan-li** [comment]
same problem, have you resolved it ?

**Comment by pKrime** [comment]
Hi, I have not fixed those issues yet: the silver bullet would be rewriting RigNet and converting the model so that no additional dependencies are required, but I had no time during the past months.

the user Eritojai, has shared how he made it work on this [blenderartist thread](https://blenderartists.org/t/brignet-neural-rigging-for-blender/1267223/23)

> **Before Blender / setting env thing :**
>
> -  Install Python 3.7.7 (and dont forget using Blender 2.90 later, because i use 2.83 previously)
> -  Check cuda version in powershell with command
>    nvcc --version
> - Then proceed to install like Rignet Setup installion, but i change it to pytorch 1.7.0 instead and other torch libraries adjusted accordingly
>    Edit : i’m using open3d==0.11.2
>
> conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
> pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
> pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
> pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
> pip install torch-geometric
>
> **Going to Blender :**
> After installing the addon, and i already make sure the Rignet work fine after running the Quick_start.py like stated in Rignet Github tuts , And Following all the steps in bRigNet github tutorial
> then i install the pytorch 1.7.0 too , to blender with
>
> `.\bin\python -m pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`
>
> and dont forgot all the libraries too
>
> `.\bin\python -m pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html`
>
> and other 4 (sparse, spline-conv, Cluster, Geometric )

did any of that help?

**Comment by fire** [comment]
Is there some way you can package a self contained blender archive? It's very difficult to get setup.

**Comment by pKrime** [comment]
Hi,

I tried, but I ended up with about 2GB in dependencies, and it's not even guaranteed to work due to differences in system environment: if virtualenv+pip don't work, there are reasons to think that my packaging wouldn't either.

Hang on, I'm planning to be back on this tool as soon as possible

**Comment by fire** [comment]
2GB uncompressed isn't that large in the large scheme of things. Text and binary code is compressible. It can be handled by Google Drive.

**Comment by pKrime** [comment]
Hi,

the main issue with a prepackaged bundle is that you might need different builds of pytorch, depending on your system anc cuda version.

I have added an autoinstall button in the latest release, I'm afraid it's the best I can do for now.

I will look for more efficient solutions in the future

Cheers,
Paolo
