### ISSUE TITLE
colud u please tell me how to make maximo anmaition and rigged model together，and output a amimated model，like.fbx？

### ISSUE THREAD

**Issue by kenchikuliu** [pKrime/brignet#8]

**Comment by pKrime** [comment]
Hi kenchikuliu,

that's the easier part: Mixamo will handle rigs that abide to its structure and name convention. Please, download any Mixamo character and replicate it's bone names and hierarchy on yours, then upload to the Mixamo website.

Mixamo will handle the rest, just keep in mind that animation packages come with a different rest pose
