### ISSUE TITLE
What should I run to get rigged .fbx file from python script using blender?

### ISSUE THREAD

**Issue by kashyappiyush1998** [pKrime/brignet#9]
I want to use blender inside my python code. I have generated a text file and I have the obj file for the mesh. What part of this code should I run to get rigged mesh as output.

**Comment by pKrime** [comment]
Hi,

you should be able to load your character from the load skeleton section of the bRigNet panel. If you want to use this operator inside a python script, these lines should do

```
wm = context.window_manager

wm.brignet_obj_path = "PATH_TO_YOUR_OBJ"
wm.brignet_skel_path = "PATH_TO_YOUR_TEXT_FILE"

bpy.ops.object.brignet_load()
```

cheers,
p.
